### ISSUE TITLE
"Press ENTER or type command to continue" message

### ISSUE THREAD

**Issue by etihwnad** [Dalker/vim-now#1]
Loading this plugin causes all startups of vim to give this message before redrawing the screen.

Somewhere there is a command run while loading that (vim thinks) generates output and is waiting for that output to be read.

The effect happens in `plugin/now.vim` somewhere.

**Comment by Dalker** [comment]
presumably solved by the code provided by @etihwnad , even though I didn't see the problem myself (possibly due to differing versions of vim or different flags when vim was compiled)
